name: redis
deploymentConfigs:
- containers:
  - image: containscafeine/redis-test:centos
    env:
    - name: MASTER
      value: "true"
    resources:
      requests:
        memory: "10Mi"

services:
- portMappings:
  - "6379"
